// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmlzsviwvjmlqalibwiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtbHpzdml3dmptbHFhbGlid2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMzM5NDgsImV4cCI6MjA1MjcwOTk0OH0.A2o9S3gBP-d2uffZQc2xanrpykpMiO5354FahWnv-Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);